version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - smolathon

  frontend:
    build:
      context: ./src/smolensk-codd
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - api
    networks:
      - smolathon

networks:
  smolathon:
    driver: bridge


